In [11]:
from yelpapi import YelpAPI
yelp_api = YelpAPI("###apikey")

import pandas as pd

In [67]:
data = pd.read_csv("DOHMH_New_York_City_Restaurant_Inspection_Results.csv.crdownload")

In [68]:
data.head()

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,VIOLATION DESCRIPTION,CRITICAL FLAG,SCORE,GRADE,GRADE DATE,RECORD DATE,INSPECTION TYPE
0,41142210,BARBOUNIA,MANHATTAN,250,PARK AVENUE SOUTH,10003.0,2129950242,Mediterranean,04/05/2017,Violations were cited in the following area(s).,02G,Cold food item held above 41Âº F (smoked fish ...,Critical,13.0,A,04/05/2017,10/17/2018,Cycle Inspection / Re-inspection
1,40548766,JOE'S SHANGHAI RESTAURANT,MANHATTAN,9,PELL STREET,10013.0,2122338888,Chinese,07/02/2018,Violations were cited in the following area(s).,10B,Plumbing not properly installed or maintained;...,Not Critical,17.0,B,07/02/2018,10/17/2018,Cycle Inspection / Re-inspection
2,50017903,JACK'S WIFE FREDA,MANHATTAN,50,CARMINE ST,10014.0,6466699877,Mediterranean,06/14/2018,Violations were cited in the following area(s).,10F,Non-food contact surface improperly constructe...,Not Critical,10.0,A,06/14/2018,10/17/2018,Cycle Inspection / Re-inspection
3,41685823,ATOMIC WINGS,MANHATTAN,311,BROADWAY,10007.0,2125717667,Chicken,07/14/2017,Violations were cited in the following area(s).,16D,"Posted caloric content on the menu(s), menu bo...",Not Critical,NaN,NaN,NaN,10/17/2018,Calorie Posting / Initial Inspection
4,41156699,WOOLWORTH TOWER KITCHEN/THE WOOLY PUBLIC,MANHATTAN,233,BROADWAY,10279.0,2125712930,American,02/05/2016,Violations were cited in the following area(s).,09B,Thawing procedures improper.,Not Critical,20.0,B,02/05/2016,10/17/2018,Cycle Inspection / Re-inspection

In [69]:
data["address"] = data["BUILDING"] +" " + data["STREET"]

In [70]:
data.head()

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,VIOLATION DESCRIPTION,CRITICAL FLAG,SCORE,GRADE,GRADE DATE,RECORD DATE,INSPECTION TYPE,address
0,41142210,BARBOUNIA,MANHATTAN,250,PARK AVENUE SOUTH,10003.0,2129950242,Mediterranean,04/05/2017,Violations were cited in the following area(s).,02G,Cold food item held above 41Âº F (smoked fish ...,Critical,13.0,A,04/05/2017,10/17/2018,Cycle Inspection / Re-inspection,250 PARK AVENUE SOUTH
1,40548766,JOE'S SHANGHAI RESTAURANT,MANHATTAN,9,PELL STREET,10013.0,2122338888,Chinese,07/02/2018,Violations were cited in the following area(s).,10B,Plumbing not properly installed or maintained;...,Not Critical,17.0,B,07/02/2018,10/17/2018,Cycle Inspection / Re-inspection,9 PELL STREET
2,50017903,JACK'S WIFE FREDA,MANHATTAN,50,CARMINE ST,10014.0,6466699877,Mediterranean,06/14/2018,Violations were cited in the following area(s).,10F,Non-food contact surface improperly constructe...,Not Critical,10.0,A,06/14/2018,10/17/2018,Cycle Inspection / Re-inspection,50 CARMINE ST
3,41685823,ATOMIC WINGS,MANHATTAN,311,BROADWAY,10007.0,2125717667,Chicken,07/14/2017,Violations were cited in the following area(s).,16D,"Posted caloric content on the menu(s), menu bo...",Not Critical,NaN,NaN,NaN,10/17/2018,Calorie Posting / Initial Inspection,311 BROADWAY
4,41156699,WOOLWORTH TOWER KITCHEN/THE WOOLY PUBLIC,MANHATTAN,233,BROADWAY,10279.0,2125712930,American,02/05/2016,Violations were cited in the following area(s).,09B,Thawing procedures improper.,Not Critical,20.0,B,02/05/2016,10/17/2018,Cycle Inspection / Re-inspection,233 BROADWAY

In [ ]:
data["ZIPCODE"] = data["ZIPCODE"].apply(lambda x: int(x))

In [71]:
data = data[data["ZIPCODE"]>0]

In [72]:
data.shape

(348763, 19)

In [186]:
query_data = data[["DBA","address", "ZIPCODE"]]

In [187]:
query_data.sort_values(by="DBA", inplace=True)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [188]:
query_data.drop_duplicates(inplace=True)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [189]:
query_data.shape

(26134, 3)

In [190]:
query_data.dropna(inplace=True)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [265]:
query_data["id"] = 0
query_data["categories"]=0
query_data["coordinates"]=0
query_data["hours"]=0
query_data["image_url"]=0
query_data["is_closed"]=0
query_data["photos"]=0
query_data["price"]=0
query_data["rating"]=0
query_data["review_count"]=0
query_data["transactions"]=0

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

In [192]:
query_data

,DBA,address,ZIPCODE,id,categories,coordinates,hours,image_url,is_closed,photos,price,rating,review_count,transactions
65096,#1 Chinese Restaurant,825 W 181ST ST,10033,0,0,0,0,0,0,0,0,0,0,0
156678,#1 GARDEN CHINESE RESTAURANT,221 PROSPECT PARK W,11215,0,0,0,0,0,0,0,0,0,0,0
347563,#1 Natural Juice Bar,685 SENECA AVE,11385,0,0,0,0,0,0,0,0,0,0,0
236885,#1 SABOR LATINO RESTAURANT,4120 WHITE PLAINS ROAD,10466,0,0,0,0,0,0,0,0,0,0,0
219732,$1 PIZZA,1276 FULTON ST,11216,0,0,0,0,0,0,0,0,0,0,0
154475,$5 TO $9 RESTAURANT,7026 3RD AVE,11209,0,0,0,0,0,0,0,0,0,0,0
10436,& PIZZA,740 BROADWAY,10003,0,0,0,0,0,0,0,0,0,0,0
26749,& PIZZA,15 W 28TH ST,10001,0,0,0,0,0,0,0,0,0,0,0
128347,'CESCA,166 W 75TH ST,10023,0,0,0,0,0,0,0,0,0,0,0
292401,'WICHCRAFT,1407 BROADWAY,10018,0,0,0,0,0,0,0,0,0,0,0
33373,(LEWIS DRUG STORE) LOCANDA VINI E OLII,129 GATES AVENUE,11238,0,0,0,0,0,0,0,0,0,0,0
143196,(LIBRARY) FOUR & TWENTY BLACKBIRDS,10 GRAND ARMY PLZ,11238,0,0,0,0,0,0,0,0,0,0,0
349608,+ 81 GALLERY NEW YORK,167 ELIZABETH ST,10012,0,0,0,0,0,0,0,0,0,0,0
281508,.TAO,92 9TH AVE,10011,0,0,0,0,0,0,0,0,0,0,0
77892,1 2 3 BURGER SHOT BEER,738 10 AVENUE,10019,0,0,0,0,0,0,0,0,0,0,0
53949,1 Banana Queen,6 EAST MT EDEN AVENUE,10452,0,0,0,0,0,0,0,0,0,0,0
175749,1 DARBAR,152 EAST 46 STREET,10017,0,0,0,0,0,0,0,0,0,0,0
235585,1 EAST 66TH STREET KITCHEN,1 EAST 66 STREET,10065,0,0,0,0,0,0,0,0,0,0,0
94759,1 HOTEL BROOKLYN BRIDGE,90 FURMAN ST,11201,0,0,0,0,0,0,0,0,0,0,0
334118,1 HOTEL EMPLOYEE DINING KITCHEN #36,60 FURMAN ST,11201,0,0,0,0,0,0,0,0,0,0,0
40733,1 OAK,453 WEST 17 STREET,10011,0,0,0,0,0,0,0,0,0,0,0
294356,1 OR 8,66 SOUTH 2 STREET,11249,0,0,0,0,0,0,0,0,0,0,0
74233,1 PIKE,1 PIKE ST,10002,0,0,0,0,0,0,0,0,0,0,0
23912,1 QUETZAL,7210 NEW UTRECHT AVE,11228,0,0,0,0,0,0,0,0,0,0,0
150375,1 STOP PATTY SHOP,1708 AMSTERDAM AVENUE,10031,0,0,0,0,0,0,0,0,0,0,0
251761,1 TASTE OF INDIA,13508 LIBERTY AVE,11419,0,0,0,0,0,0,0,0,0,0,0
152015,1.5 DAK GALBI INC.,15803 NORTHERN BLVD,11358,0,0,0,0,0,0,0,0,0,0,0
143218,10 02 Lounge and Restaurant,806 E TREMONT AVE,10460,0,0,0,0,0,0,0,0,0,0,0
112810,10 BELOW ICE CREAM,10 MOTT ST,10013,0,0,0,0,0,0,0,0,0,0,0
223308,10 BELOW ICE CREAM,132 ALLEN ST,10002,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221157,ZOU'S RESTAURANT BUFFET,233 UTICA AVE,11213,0,0,0,0,0,0,0,0,0,0,0
292874,ZOUJI BBQ,4283 MAIN ST,11355,0,0,0,0,0,0,0,0,0,0,0
21840,ZU RANG,4114 162ND ST,11358,0,0,0,0,0,0,0,0,0,0,0
223449,ZU RANG NY,4114 162ND ST,11358,0,0,0,0,0,0,0,0,0,0,0
303157,ZUCCHERO E POMODORI,1435 2ND AVE,10021,0,0,0,0,0,0,0,0,0,0,0
54773,ZUCKER'S BAGELS,370 LEXINGTON AVENUE,10017,0,0,0,0,0,0,0,0,0,0,0
68014,ZUCKER'S BAGELS AND SMOKED FISH,273 COLUMBUS AVE,10023,0,0,0,0,0,0,0,0,0,0,0
235538,ZUCKER'S BAGELS AND SMOKED FISH,146 CHAMBERS STREET,10007,0,0,0,0,0,0,0,0,0,0,0
248410,ZUCKER'S BAGELS FLATIRON,40 E 23RD ST,10010,0,0,0,0,0,0,0,0,0,0,0
169613,ZUCKIS ICE CREAM PARLOR,1364 CONEY ISLAND AVE,11230,0,0,0,0,0,0,0,0,0,0,0
318263,ZUM STAMMTISCH,6946 MYRTLE AVENUE,11385,0,0,0,0,0,0,0,0,0,0,0
306357,ZUMA NEW YORK,261 MADISON AVE,10016,0,0,0,0,0,0,0,0,0,0,0
212177,ZURILEE,755 FLATBUSH AVE,11226,0,0,0,0,0,0,0,0,0,0,0
73155,ZURUTTO RAMEN & GYOZA BAR,142 W 72ND ST,10023,0,0,0,0,0,0,0,0,0,0,0
170720,ZUTTO JAPANESE AMERICAN PUB,77 HUDSON ST,10013,0,0,0,0,0,0,0,0,0,0,0
54775,ZVAH INC,37 CANAL ST,10002,0,0,0,0,0,0,0,0,0,0,0
192385,ZYARA,57 CLINTON ST,10002,0,0,0,0,0,0,0,0,0,0,0
284431,ZYARA RESTAURANT,2553 STEINWAY ST,11103,0,0,0,0,0,0,0,0,0,0,0
177927,ZYMI BAR & GRILL,726 ASTOR AVENUE,10467,0,0,0,0,0,0,0,0,0,0,0
105147,ZZ CLAM BAR,169 THOMPSON ST,10012,0,0,0,0,0,0,0,0,0,0,0
126918,ZZ'S PIZZA & GRILL,1 RICHMOND TERRACE,10301,0,0,0,0,0,0,0,0,0,0,0
25051,Zenith Thai,7002 FRESH POND RD,11385,0,0,0,0,0,0,0,0,0,0,0
297725,Zenon Taverna,3410 31ST AVE,11106,0,0,0,0,0,0,0,0,0,0,0
784,cafe paulette,1 S ELLIOTT PL,11217,0,0,0,0,0,0,0,0,0,0,0
307479,cloud social,6 W 32ND ST,10001,0,0,0,0,0,0,0,0,0,0,0
342641,energy fuel,926 FULTON STREET,11238,0,0,0,0,0,0,0,0,0,0,0
98223,mango mama,1526 COLLEGE POINT BLVD,11356,0,0,0,0,0,0,0,0,0,0,0
23551,orientalarrows LLC,266 MALCOLM X BLVD,11233,0,0,0,0,0,0,0,0,0,0,0
126004,sassy's specialty sandwiches,233 S 4TH ST,11211,0,0,0,0,0,0,0,0,0,0,0
301849,tutto il giorno,114 FRANKLIN ST,10013,0,0,0,0,0,0,0,0,0,0,0

In [6]:
def get_ids(start, stop):
    for i in range(start, stop):
        rest = query_data.iloc[i,0]
        addr = query_data.iloc[i,1]
        zip_co= query_data.iloc[i,2]
        info = yelp_api.business_match_query(name=rest,city="New York", address1 = addr, state="NY", zip_code =zip_co ,country="US")
        try:
            query_data.iloc[i,3] = info["businesses"][0]["id"]
        except:
            continue

In [271]:
get_ids(0,11)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [272]:
query_data

,DBA,address,ZIPCODE,id,categories,coordinates,hours,image_url,is_closed,photos,price,rating,review_count,transactions
65096,#1 Chinese Restaurant,825 W 181ST ST,10033,bMAsaXIDMActYCYCw0HcCQ,0,0,0,0,0,0,0,0,0,0
156678,#1 GARDEN CHINESE RESTAURANT,221 PROSPECT PARK W,11215,4PG9npz7q_LP2H5LfDjWig,0,0,0,0,0,0,0,0,0,0
347563,#1 Natural Juice Bar,685 SENECA AVE,11385,hP2XjN1DlBI894m9_KlkBA,0,0,0,0,0,0,0,0,0,0
236885,#1 SABOR LATINO RESTAURANT,4120 WHITE PLAINS ROAD,10466,99SdCUxC_mLXp60iJagT_w,0,0,0,0,0,0,0,0,0,0
219732,$1 PIZZA,1276 FULTON ST,11216,0,0,0,0,0,0,0,0,0,0,0
154475,$5 TO $9 RESTAURANT,7026 3RD AVE,11209,-s6Hasj4vw-YaxMfJCaFiA,0,0,0,0,0,0,0,0,0,0
10436,& PIZZA,740 BROADWAY,10003,51xuge-nOovXRTU_o0G0gA,0,0,0,0,0,0,0,0,0,0
26749,& PIZZA,15 W 28TH ST,10001,t0Bel7xLMUt5g8qIpBylZg,0,0,0,0,0,0,0,0,0,0
128347,'CESCA,166 W 75TH ST,10023,VUcrIqM40HWWb2sxAS9mLA,0,0,0,0,0,0,0,0,0,0
292401,'WICHCRAFT,1407 BROADWAY,10018,_dJBogcWfMC2Fe2Um0PntA,0,0,0,0,0,0,0,0,0,0
33373,(LEWIS DRUG STORE) LOCANDA VINI E OLII,129 GATES AVENUE,11238,53ZNJNrT91VgvrI0LFjLNQ,0,0,0,0,0,0,0,0,0,0
143196,(LIBRARY) FOUR & TWENTY BLACKBIRDS,10 GRAND ARMY PLZ,11238,"[{'alias': 'bakeries', 'title': 'Bakeries'}, {...",0,0,0,0,0,0,0,0,0,0
349608,+ 81 GALLERY NEW YORK,167 ELIZABETH ST,10012,0,0,0,0,0,0,0,0,0,0,0
281508,.TAO,92 9TH AVE,10011,"[{'alias': 'lounges', 'title': 'Lounges'}]",0,0,0,0,0,0,0,0,0,0
77892,1 2 3 BURGER SHOT BEER,738 10 AVENUE,10019,"[{'alias': 'burgers', 'title': 'Burgers'}, {'a...",0,0,0,0,0,0,0,0,0,0
53949,1 Banana Queen,6 EAST MT EDEN AVENUE,10452,"[{'alias': 'healthmarkets', 'title': 'Health M...",0,0,0,0,0,0,0,0,0,0
175749,1 DARBAR,152 EAST 46 STREET,10017,"[{'alias': 'indpak', 'title': 'Indian'}, {'ali...",0,0,0,0,0,0,0,0,0,0
235585,1 EAST 66TH STREET KITCHEN,1 EAST 66 STREET,10065,0,0,0,0,0,0,0,0,0,0,0
94759,1 HOTEL BROOKLYN BRIDGE,90 FURMAN ST,11201,"[{'alias': 'hotels', 'title': 'Hotels'}, {'ali...",0,0,0,0,0,0,0,0,0,0
334118,1 HOTEL EMPLOYEE DINING KITCHEN #36,60 FURMAN ST,11201,"[{'alias': 'hotels', 'title': 'Hotels'}, {'ali...",0,0,0,0,0,0,0,0,0,0
40733,1 OAK,453 WEST 17 STREET,10011,"[{'alias': 'danceclubs', 'title': 'Dance Clubs...",0,0,0,0,0,0,0,0,0,0
294356,1 OR 8,66 SOUTH 2 STREET,11249,"[{'alias': 'japanese', 'title': 'Japanese'}, {...",0,0,0,0,0,0,0,0,0,0
74233,1 PIKE,1 PIKE ST,10002,"[{'alias': 'cafes', 'title': 'Cafes'}, {'alias...",0,0,0,0,0,0,0,0,0,0
23912,1 QUETZAL,7210 NEW UTRECHT AVE,11228,0,0,0,0,0,0,0,0,0,0,0
150375,1 STOP PATTY SHOP,1708 AMSTERDAM AVENUE,10031,"[{'alias': 'caribbean', 'title': 'Caribbean'},...",0,0,0,0,0,0,0,0,0,0
251761,1 TASTE OF INDIA,13508 LIBERTY AVE,11419,0,0,0,0,0,0,0,0,0,0,0
152015,1.5 DAK GALBI INC.,15803 NORTHERN BLVD,11358,"[{'alias': 'korean', 'title': 'Korean'}]",0,0,0,0,0,0,0,0,0,0
143218,10 02 Lounge and Restaurant,806 E TREMONT AVE,10460,0,0,0,0,0,0,0,0,0,0,0
112810,10 BELOW ICE CREAM,10 MOTT ST,10013,"[{'alias': 'icecream', 'title': 'Ice Cream & F...",0,0,0,0,0,0,0,0,0,0
223308,10 BELOW ICE CREAM,132 ALLEN ST,10002,"[{'alias': 'icecream', 'title': 'Ice Cream & F...",0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221157,ZOU'S RESTAURANT BUFFET,233 UTICA AVE,11213,0,0,0,0,0,0,0,0,0,0,0
292874,ZOUJI BBQ,4283 MAIN ST,11355,0,0,0,0,0,0,0,0,0,0,0
21840,ZU RANG,4114 162ND ST,11358,0,0,0,0,0,0,0,0,0,0,0
223449,ZU RANG NY,4114 162ND ST,11358,0,0,0,0,0,0,0,0,0,0,0
303157,ZUCCHERO E POMODORI,1435 2ND AVE,10021,0,0,0,0,0,0,0,0,0,0,0
54773,ZUCKER'S BAGELS,370 LEXINGTON AVENUE,10017,0,0,0,0,0,0,0,0,0,0,0
68014,ZUCKER'S BAGELS AND SMOKED FISH,273 COLUMBUS AVE,10023,0,0,0,0,0,0,0,0,0,0,0
235538,ZUCKER'S BAGELS AND SMOKED FISH,146 CHAMBERS STREET,10007,0,0,0,0,0,0,0,0,0,0,0
248410,ZUCKER'S BAGELS FLATIRON,40 E 23RD ST,10010,0,0,0,0,0,0,0,0,0,0,0
169613,ZUCKIS ICE CREAM PARLOR,1364 CONEY ISLAND AVE,11230,0,0,0,0,0,0,0,0,0,0,0
318263,ZUM STAMMTISCH,6946 MYRTLE AVENUE,11385,0,0,0,0,0,0,0,0,0,0,0
306357,ZUMA NEW YORK,261 MADISON AVE,10016,0,0,0,0,0,0,0,0,0,0,0
212177,ZURILEE,755 FLATBUSH AVE,11226,0,0,0,0,0,0,0,0,0,0,0
73155,ZURUTTO RAMEN & GYOZA BAR,142 W 72ND ST,10023,0,0,0,0,0,0,0,0,0,0,0
170720,ZUTTO JAPANESE AMERICAN PUB,77 HUDSON ST,10013,0,0,0,0,0,0,0,0,0,0,0
54775,ZVAH INC,37 CANAL ST,10002,0,0,0,0,0,0,0,0,0,0,0
192385,ZYARA,57 CLINTON ST,10002,0,0,0,0,0,0,0,0,0,0,0
284431,ZYARA RESTAURANT,2553 STEINWAY ST,11103,0,0,0,0,0,0,0,0,0,0,0
177927,ZYMI BAR & GRILL,726 ASTOR AVENUE,10467,0,0,0,0,0,0,0,0,0,0,0
105147,ZZ CLAM BAR,169 THOMPSON ST,10012,0,0,0,0,0,0,0,0,0,0,0
126918,ZZ'S PIZZA & GRILL,1 RICHMOND TERRACE,10301,0,0,0,0,0,0,0,0,0,0,0
25051,Zenith Thai,7002 FRESH POND RD,11385,0,0,0,0,0,0,0,0,0,0,0
297725,Zenon Taverna,3410 31ST AVE,11106,0,0,0,0,0,0,0,0,0,0,0
784,cafe paulette,1 S ELLIOTT PL,11217,0,0,0,0,0,0,0,0,0,0,0
307479,cloud social,6 W 32ND ST,10001,0,0,0,0,0,0,0,0,0,0,0
342641,energy fuel,926 FULTON STREET,11238,0,0,0,0,0,0,0,0,0,0,0
98223,mango mama,1526 COLLEGE POINT BLVD,11356,0,0,0,0,0,0,0,0,0,0,0
23551,orientalarrows LLC,266 MALCOLM X BLVD,11233,0,0,0,0,0,0,0,0,0,0,0
126004,sassy's specialty sandwiches,233 S 4TH ST,11211,0,0,0,0,0,0,0,0,0,0,0
301849,tutto il giorno,114 FRANKLIN ST,10013,0,0,0,0,0,0,0,0,0,0,0

In [275]:
get_ids(11,50)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [202]:
get_ids(50,200)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [207]:
get_ids(200,300)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [209]:
get_ids(300,1000)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [217]:
get_ids(1000,1100)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [224]:
get_ids(1100,1200)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [226]:
get_ids(1100,1300)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [228]:
get_ids(1300,1400)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [230]:
get_ids(1400,1500)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [231]:
get_ids(1500,1600)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [233]:
get_ids(1600,1700)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [235]:
get_ids(1700,2000)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [310]:
get_ids(2000,2500)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [18]:
get_ids(2500, 3000)

In [22]:
get_ids(3000, 3500)

In [47]:
get_ids(3500, 4000)

In [52]:
get_ids(4000, 4500)

In [55]:
get_ids(4500, 5000)

In [64]:
get_ids(5000, 5238)

In [70]:
get_ids(5239, 5500)

In [77]:
get_ids(5500, 5750)

In [17]:
get_ids(5750, 6000)

In [24]:
get_ids(6000,6500)

In [30]:
get_ids(6500,7000)

In [36]:
get_ids(7000,7500)

In [42]:
get_ids(7500,8000)

In [19]:
get_ids(8000,8166)

In [23]:
get_ids(8167,8500)

In [33]:
get_ids(8500,9000)

In [41]:
get_ids(9000,9500)

In [50]:
get_ids(9500,10000)

In [59]:
get_ids(10000,10401)

In [74]:
get_ids(10402, 10500)

In [82]:
get_ids(10500, 11000)

In [89]:
get_ids(11000, 11500)

In [101]:
get_ids(11500, 12000)

In [106]:
get_ids(12000, 12500)

In [111]:
get_ids(12500, 12560)

In [114]:
get_ids(12560, 13000)

In [120]:
get_ids(13000, 13500)

In [126]:
get_ids(13500, 14000)

In [131]:
get_ids(14000,14500)

In [137]:
get_ids(14500,15000)

In [16]:
get_ids(15000,15398)

In [1]:
get_ids(15399,16000)

In [41]:
get_ids(15900,16000)

In [2]:
get_ids(16000,16500)

In [77]:
get_ids(16460, 16500)

In [86]:
get_ids(16500,16600)

In [88]:
get_ids(16600,16700)

In [90]:
get_ids(16700, 17000)

In [98]:
get_ids(17000, 17500)

In [104]:
get_ids(17500, 18000)

In [111]:
get_ids(18000, 18500)

In [117]:
get_ids(18500, 19000)

In [1]:
get_ids(19000, 19029)

In [17]:
get_ids(19028, 19500)

In [25]:
get_ids(19500, 20000)

In [31]:
get_ids(20000, 20500)

In [37]:
get_ids(20500, 21000)

In [57]:
get_ids(21000,21500)

In [61]:
get_ids(21500, 21567)

In [90]:
get_ids(21567,22000)

In [96]:
get_ids(22000,22500)

In [104]:
get_ids(22500,23000)

In [2]:
get_ids(23000,23500)

In [124]:
get_ids(23456,23500)

In [135]:
get_ids(23500,24000)

In [141]:
get_ids(24000,24128)

In [3]:
get_ids(24128,24500)

In [149]:
get_ids(24434,24500)

In [155]:
get_ids(24500,25000)

In [163]:
get_ids(25000,25755)

In [9]:
def get_info(start, stop):
    for i in range(start, stop):
        id_curr = query_data.iloc[i,3]
        if id_curr == 0:
            continue
        try:
            curr = yelp_api.business_query(id=id_curr)
        except:
            continue
        try:
            query_data.iloc[i,4] = str(curr["categories"])
        except:
            pass
        try:
            query_data.iloc[i,5] = str(curr["coordinates"])
        except:
            pass
        try:
            query_data.iloc[i,6] = str(curr["hours"])
        except:
            pass
        try:
            query_data.iloc[i,7] = str(curr["image_url"])
        except:
            pass
        try:
            query_data.iloc[i,8] = str(curr["is_closed"])
        except:
            pass
        try:
            query_data.iloc[i,9] = str(curr["photos"])
        except:
            pass
        try:
            query_data.iloc[i,10] = str(curr["price"])
        except:
            pass
        try:
            query_data.iloc[i,11] = str(curr['rating'])
        except:
            pass
        try:
            query_data.iloc[i,12] = str(curr['review_count'])
        except:
            pass
        try:
            query_data.iloc[i,13] = str(curr['transactions'])
        except:
            pass

In [277]:
get_info(0,10)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [291]:
get_info(10,50)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [293]:
get_info(50,200)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [296]:
get_info(200,500)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [299]:
get_info(500,1000)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [302]:
get_info(1000,1500)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [305]:
get_info(1500,2000)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [316]:
get_info(2000,2500)

/Users/elizabethoriordan/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [29]:
get_info(2500,3000)

In [43]:
get_info(3000,3100)

In [45]:
get_info(3100,3500)

In [49]:
get_info(3500,4000)

In [53]:
get_info(4000,4500)

In [57]:
get_info(4500,5000)

In [74]:
get_info(5000,5500)

In [14]:
get_info(5500,5750)

In [20]:
get_info(5750,6000)

In [27]:
get_info(6000,6500)

In [33]:
get_info(6500,7000)

In [39]:
get_info(7000,7500)

In [45]:
get_info(7500,7800)

In [11]:
get_info(7800,8000)

In [29]:
get_info(8000,8500)

In [37]:
get_info(8500, 9000)

In [44]:
get_info(9000,9500)

In [53]:
get_info(9500,10000)

In [76]:
get_info(10000,10500)

In [85]:
get_info(10500,11000)

In [94]:
get_info(11000,11500)

In [103]:
get_info(11500,12000)

In [108]:
get_info(12000,12500)

In [117]:
get_info(12500,13000)

In [123]:
get_info(13000,13500)

In [128]:
get_info(13500,14000)

In [134]:
get_info(14000,14500)

In [139]:
get_info(14500,14900)

In [144]:
get_info(14900,14945)

In [11]:
get_info(14945,15000)

In [56]:
get_info(15000,15500)

In [61]:
get_info(15500,16000)

In [81]:
get_info(16000,16500)

In [95]:
get_info(16500, 17000)

In [101]:
get_info(17000, 17500)

In [107]:
get_info(17500,18000)

In [114]:
get_info(18000,18500)

In [120]:
get_info(18500, 19000)

In [22]:
get_info(19000,19500)

In [28]:
get_info(19500, 20000)

In [34]:
get_info(20000,20500)

In [41]:
get_info(20500,21000)

In [59]:
get_info(21000,21500)

In [93]:
get_info(21500,22000)

In [99]:
get_info(22000,22500)

In [107]:
get_info(22500,23000)

In [127]:
get_info(23000,23500)

In [138]:
get_info(23500,24000)

In [152]:
get_info(24000,24500)

In [158]:
get_info(24500,25000)

In [168]:
get_info(25000,25755)

In [ ]:
query_data.to_csv("Oct242018.csv")

## Get Rat Data

In [1]:
import pandas as pd

In [2]:
rats = pd.read_csv("Rodent_Inspection.csv.crdownload")

In [3]:
rats

,INSPECTION_TYPE,JOB_TICKET_OR_WORK_ORDER_ID,JOB_ID,JOB_PROGRESS,BBL,BORO_CODE,BLOCK,LOT,HOUSE_NUMBER,STREET_NAME,ZIP_CODE,X_COORD,Y_COORD,LATITUDE,LONGITUDE,BOROUGH,INSPECTION_DATE,RESULT,APPROVED_DATE,LOCATION
0,BAIT,1,PO12965,3,1011470035,1,1147,35,104,WEST 76 STREET,10023.0,990505.0,223527.0,40.780204,-73.977414,Manhattan,10/14/2009 12:00:27 PM,Bait applied,10/14/2009 03:01:46 PM,"(40.7802039792471, -73.9774144709456)"
1,BAIT,2,PO12966,3,1011470034,1,1147,34,102,WEST 76 STREET,10023.0,990516.0,223521.0,40.780188,-73.977375,Manhattan,10/14/2009 12:51:21 PM,Bait applied,10/14/2009 03:02:30 PM,"(40.7801875030438, -73.977374757787)"
2,BAIT,30,PO16966,3,2043370027,2,4337,27,620,THWAITES PLACE,10467.0,1020110.0,252216.0,40.858877,-73.870364,Bronx,11/09/2009 12:59:55 PM,Bait applied,11/10/2009 02:54:52 PM,"(40.8588765781972, -73.8703636422023)"
3,BAIT,31,PO13665,3,2037670077,2,3767,77,1227,WHITEPLAINS ROAD,10472.0,1022441.0,242180.0,40.831321,-73.861994,Bronx,11/09/2009 11:10:16 AM,Bait applied,11/10/2009 02:56:42 PM,"(40.8313209626148, -73.861994089899)"
4,BAIT,38,PO11291,3,1011690057,1,1169,57,2199,BROADWAY,10024.0,989641.0,224567.0,40.783059,-73.980533,Manhattan,11/10/2009 08:40:42 AM,Bait applied,11/17/2009 11:39:11 AM,"(40.7830590725833, -73.9805333640688)"
5,BAIT,39,PO12483,3,1015340012,1,1534,12,232,EAST 89 STREET,10128.0,997617.0,223597.0,40.780388,-73.951734,Manhattan,11/10/2009 09:53:06 AM,Bait applied,11/17/2009 11:39:42 AM,"(40.780388216313, -73.9517343542567)"
6,BAIT,41,PO25356,3,1015860005,1,1586,5,515,EAST 89 STREET,10128.0,999449.0,222589.0,40.777619,-73.945122,Manhattan,11/10/2009 09:00:51 AM,Bait applied,11/17/2009 11:35:04 AM,"(40.7776185626037, -73.9451216392382)"
7,BAIT,46,PO16381,3,2028140048,2,2814,48,1952,ANTHONY AVENUE,10457.0,1011143.0,249042.0,40.850197,-73.902793,Bronx,11/16/2009 12:59:45 PM,Bait applied,11/16/2009 04:20:18 PM,"(40.8501967689145, -73.9027926637706)"
8,BAIT,48,PO11801,3,2026930022,2,2693,22,1230,PROSPECT AVENUE,10459.0,1012333.0,240622.0,40.827083,-73.898527,Bronx,11/16/2009 12:06:24 PM,Bait applied,11/16/2009 04:19:27 PM,"(40.8270826259387, -73.8985265540885)"
9,BAIT,50,PO11803,3,2026930008,2,2693,8,1198,PROSPECT AVENUE,10459.0,1012297.0,240506.0,40.826764,-73.898657,Bronx,11/16/2009 11:50:25 AM,Bait applied,11/16/2009 04:20:04 PM,"(40.8267643536103, -73.8986571191557)"
10,BAIT,51,PO11817,3,1003770026,1,377,26,390,EAST 8 STREET,10009.0,990654.0,203066.0,40.724044,-73.976896,Manhattan,11/16/2009 09:55:20 PM,Bait applied,11/19/2009 12:09:49 PM,"(40.7240436116555, -73.976895948583)"
11,BAIT,52,PO11077,3,1003890019,1,389,19,202,EAST 7 STREET,10009.0,989741.0,203281.0,40.724634,-73.980190,Manhattan,11/16/2009 10:20:14 PM,Bait applied,11/23/2009 12:11:55 PM,"(40.7246343483455, -73.980189651703)"
12,BAIT,53,PO15241,3,1004590040,1,459,40,19,EAST 3 STREET,10003.0,986804.0,203770.0,40.725978,-73.990786,Manhattan,11/16/2009 09:25:46 PM,Bait applied,11/19/2009 12:04:34 PM,"(40.7259778701156, -73.9907855310067)"
13,BAIT,57,PO10580,3,1002100005,1,210,5,336,CANAL STREET,10013.0,983586.0,201500.0,40.719748,-74.002395,Manhattan,11/17/2009 12:00:29 PM,Bait applied,11/23/2009 12:16:37 PM,"(40.7197476131092, -74.0023953936767)"
14,BAIT,58,PO13111,3,1003920010,1,392,10,350,EAST 10 STREET,10009.0,989987.0,203999.0,40.726605,-73.979302,Manhattan,11/17/2009 09:55:24 AM,Bait applied,11/23/2009 12:07:54 PM,"(40.726604927718, -73.9793015244998)"
15,BAIT,59,PO10759,3,1004290001,1,429,1,12,1 AVENUE,10009.0,987488.0,202831.0,40.723400,-73.988318,Manhattan,11/17/2009 10:30:04 AM,Bait applied,11/23/2009 02:11:19 PM,"(40.7234003190272, -73.9883182080389)"
16,BAIT,60,PO11965,3,1004420011,1,442,11,31,EAST 1 STREET,10003.0,986933.0,203069.0,40.724054,-73.990320,Manhattan,11/17/2009 11:02:47 AM,Bait applied,11/19/2009 08:10:36 AM,"(40.7240537571041, -73.9903203968151)"
17,BAIT,61,PO11019,3,1004470009,1,447,9,306,EAST 6 STREET,10003.0,987552.0,204216.0,40.727202,-73.988087,Manhattan,11/17/2009 09:20:23 AM,Bait applied,11/19/2009 08:21:54 AM,"(40.7272017839871, -73.9880866345106)"
18,BAIT,63,PO10782,3,1019180023,1,1918,23,119,WEST 133 STREET,10030.0,1000136.0,235540.0,40.813164,-73.942610,Manhattan,11/18/2009 09:15:05 AM,Bait applied,11/19/2009 12:13:18 PM,"(40.8131643309274, -73.9426104832865)"
19,BAIT,66,PO10165,3,1020690042,1,2069,42,880,ST NICHOLAS AVENUE,10032.0,1000384.0,241691.0,40.830047,-73.941700,Manhattan,11/18/2009 09:55:02 AM,Bait applied,11/19/2009 12:16:57 PM,"(40.8300466340453, -73.941699773442)"
20,BAIT,73,PO13732,3,1021110099,1,2111,99,446,WEST 167 STREET,10032.0,1001797.0,244793.0,40.838558,-73.936586,Manhattan,11/20/2009 01:13:12 PM,Bait applied,11/23/2009 11:03:56 AM,"(40.8385580327087, -73.936585783534)"
21,BAIT,77,PO13369,3,1021310035,1,2131,35,534,WEST 175 STREET,10033.0,1002298.0,247020.0,40.844669,-73.934769,Manhattan,11/20/2009 09:15:56 AM,Bait applied,11/23/2009 11:12:45 AM,"(40.844669486257, -73.9347691952077)"
22,BAIT,84,PO12817,3,1004510053,1,451,53,317,EAST 9 STREET,10003.0,987961.0,204844.0,40.728925,-73.986611,Manhattan,11/20/2009 09:23:04 AM,Bait applied,11/23/2009 12:04:48 PM,"(40.7289253286763, -73.9866106472347)"
23,BAIT,85,PO14758,3,1004540031,1,454,31,342,EAST 13 STREET,10003.0,988579.0,205673.0,40.731200,-73.984380,Manhattan,11/20/2009 09:50:22 AM,Bait applied,11/23/2009 11:28:57 AM,"(40.7312004499725, -73.9843803591535)"
24,BAIT,88,PO11791,3,1014680033,1,1468,33,486,EAST 74 STREET,10021.0,997179.0,219224.0,40.768386,-73.953324,Manhattan,11/20/2009 10:35:30 PM,Bait applied,11/23/2009 11:33:28 AM,"(40.768386131078, -73.9533243006866)"
25,BAIT,90,PO11841,3,1015570034,1,1557,34,332,EAST 95 STREET,10128.0,999013.0,224617.0,40.783186,-73.946691,Manhattan,11/20/2009 11:25:55 AM,Bait applied,11/23/2009 11:34:22 AM,"(40.7831856237632, -73.946691428707)"
26,BAIT,91,PO11717,3,1016140013,1,1614,13,21,EAST 108 STREET,10029.0,998291.0,229005.0,40.795231,-73.949289,Manhattan,11/20/2009 12:10:31 PM,Bait applied,11/23/2009 11:51:49 AM,"(40.7952306804656, -73.9492893669947)"
27,BAIT,101,PO14335,3,1011290002,1,1129,2,57,WEST 76 STREET,10023.0,991001.0,223260.0,40.779471,-73.975624,Manhattan,11/23/2009 10:55:40 AM,Bait applied,11/24/2009 03:54:45 PM,"(40.7794707699529, -73.9756237844939)"
28,BAIT,103,PO10576,3,1011540101,1,1154,101,249,WEST 62 STREET,10023.0,987539.0,221028.0,40.773346,-73.988125,Manhattan,11/23/2009 09:55:08 AM,Bait applied,11/24/2009 03:57:02 PM,"(40.77334648331, -73.9881253149363)"
29,BAIT,105,PO12629,3,1011650005,1,1165,5,269,WEST 73 STREET,10023.0,988921.0,223504.0,40.780142,-73.983134,Manhattan,11/23/2009 10:30:25 AM,Bait applied,11/24/2009 04:00:12 PM,"(40.7801418293715, -73.9831339876533)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1533493,INITIAL,1821958,PO1821958,1,3017930060,3,1793,60,493,GREENE AVENUE,11216.0,997714.0,190154.0,40.688598,-73.951448,Brooklyn,10/05/2018 12:00:27 PM,Passed Inspection,10/15/2018 09:30:07 AM,"(40.6885979500753, -73.9514476983316)"
1533494,COMPLIANCE,1817834,PO1786755,2,1007970001,1,797,1,169,W 21ST ST,10011.0,985486.0,209748.0,40.742380,-73.995540,Manhattan,10/10/2018 04:21:02 PM,Active Rat Signs,10/15/2018 11:53:16 AM,"(40.742379576192, -73.995539570337)"
1533495,INITIAL,1820883,PO1820883,1,3012200006,3,1220,6,625,NOSTRAND AVENUE,11216.0,998213.0,185429.0,40.675628,-73.949659,Brooklyn,10/11/2018 12:21:17 PM,Passed Inspection,10/15/2018 09:53:24 AM,"(40.6756275054558, -73.9496594734127)"
1533496,COMPLIANCE,1829636,PO1815107,2,1014720034,1,1472,34,440,EAST 78 STREET,10075.0,997487.0,220263.0,40.771231,-73.952210,Manhattan,10/11/2018 01:06:06 PM,Active Rat Signs,10/15/2018 02:31:46 PM,"(40.771230857257, -73.952210042055)"
1533497,INITIAL,1829273,PO1829273,1,3049500069,3,4950,69,1255,NEW YORK AVENUE,11203.0,999396.0,173267.0,40.642244,-73.945423,Brooklyn,10/09/2018 02:06:33 PM,Passed Inspection,10/15/2018 04:08:03 PM,"(40.6422435616783, -73.9454229544913)"
1533498,INITIAL,1824018,PO1824018,1,3031580111,3,3158,111,124,GEORGE STREET,11237.0,1003867.0,195512.0,40.703292,-73.929245,Brooklyn,10/12/2018 11:25:10 AM,Passed Inspection,10/15/2018 09:47:47 AM,"(40.7032918155221, -73.9292451884288)"
1533499,INITIAL,1826049,PO1826049,1,3051020099,3,5102,99,2104,ALBEMARLE TERRACE,11226.0,995511.0,175504.0,40.648389,-73.959418,Brooklyn,10/05/2018 12:00:20 PM,Passed Inspection,10/15/2018 02:14:42 PM,"(40.6483885295262, -73.9594179535796)"
1533500,COMPLIANCE,1805141,PO1782550,2,3050540060,3,5054,60,155,WOODRUFF AVENUE,11226.0,995062.0,177682.0,40.654359,-73.961034,Brooklyn,09/28/2018 03:08:53 PM,Passed Inspection,10/15/2018 12:16:12 PM,"(40.654359189467, -73.961033743383)"
1533501,INITIAL,1829281,PO1829281,1,3049500079,3,4950,79,1235,NEW YORK AVENUE,11203.0,999380.0,173466.0,40.642789,-73.945481,Brooklyn,10/09/2018 02:29:18 PM,Passed Inspection,10/15/2018 04:09:43 PM,"(40.64278879391, -73.9454805237007)"
1533502,COMPLIANCE,1828705,PO1806733,2,1007190046,1,719,46,404,WEST 22 STREET,10011.0,983606.0,211076.0,40.746037,-74.002331,Manhattan,10/10/2018 02:45:05 PM,Active Rat Signs,10/15/2018 11:53:13 AM,"(40.7460374445209, -74.0023313755682)"
1533503,INITIAL,1820817,PO1820817,1,3012170017,3,1217,17,960,BERGEN STREET,11216.0,996675.0,185714.0,40.676410,-73.955204,Brooklyn,10/10/2018 10:40:24 AM,Passed Inspection,10/15/2018 08:35:49 AM,"(40.6764100979586, -73.9552043248748)"
1533504,INITIAL,1829207,PO1829207,1,3049670007,3,4967,7,3316,AVENUE D,11203.0,999515.0,172797.0,40.640953,-73.944995,Brooklyn,10/05/2018 04:26:05 PM,Passed Inspection,10/15/2018 03:52:53 PM,"(40.6409529735475, -73.9449953088932)"
1533505,INITIAL,1813490,PO1813490,1,1011280156,1,1128,156,46,WEST 76 STREET,10023.0,990828.0,223259.0,40.779471,-73.976246,Manhattan,10/10/2018 11:58:25 AM,Passed Inspection,10/15/2018 08:59:41 AM,"(40.7794707876916, -73.9762461237453)"
1533506,INITIAL,1826022,PO1826022,1,3051020028,3,5102,28,916,FLATBUSH AVENUE,11226.0,995699.0,175798.0,40.649194,-73.958741,Brooklyn,10/03/2018 03:35:56 PM,Passed Inspection,10/15/2018 02:00:30 PM,"(40.6491937837332, -73.9587411123207)"
1533507,INITIAL,1824064,PO1824064,1,3031600041,3,3160,41,25,JEFFERSON STREET,11206.0,1002328.0,193508.0,40.697796,-73.934802,Brooklyn,10/11/2018 12:37:48 PM,Passed Inspection,10/15/2018 09:45:38 AM,"(40.6977955091861, -73.9348020440815)"
1533508,INITIAL,1820928,PO1820928,1,3012250021,3,1225,21,62,ROGERS AVENUE,11216.0,997270.0,185103.0,40.674734,-73.953060,Brooklyn,10/12/2018 02:47:30 PM,Passed Inspection,10/15/2018 09:53:19 AM,"(40.6747335867816, -73.9530595886811)"
1533509,INITIAL,1820824,PO1820824,1,3012170024,3,1217,24,972,BERGEN STREET,11216.0,996801.0,185679.0,40.676315,-73.954751,Brooklyn,10/10/2018 11:29:59 AM,Passed Inspection,10/15/2018 08:36:07 AM,"(40.6763153306234, -73.9547512110061)"
1533510,INITIAL,1821764,PO1821764,1,3017550032,3,1755,32,874,MYRTLE AVENUE,11206.0,998911.0,192625.0,40.695378,-73.947126,Brooklyn,10/11/2018 11:23:48 AM,Passed Inspection,10/15/2018 09:33:36 AM,"(40.6953775590126, -73.9471264706108)"
1533511,INITIAL,1829075,PO1829075,1,3087010031,3,8701,31,110,NEPTUNE AVENUE,11235.0,996047.0,151385.0,40.582184,-73.957527,Brooklyn,10/10/2018 02:35:17 PM,Active Rat Signs,10/15/2018 10:22:48 AM,"(40.5821840862961, -73.9575269150104)"
1533512,INITIAL,1821925,PO1821925,1,3017930026,3,1793,26,270,CLIFTON PLACE,11216.0,997143.0,190172.0,40.688646,-73.953507,Brooklyn,10/05/2018 08:19:06 AM,Passed Inspection,10/15/2018 09:30:20 AM,"(40.6886462697131, -73.9535065706364)"
1533513,INITIAL,1817014,PO1817014,1,5003760268,5,376,268,64,WESTCOTT BOULEVARD,10314.0,948732.0,164757.0,40.618818,-74.127938,Staten Island,10/12/2018 10:45:57 AM,Passed Inspection,10/15/2018 10:01:50 AM,"(40.618818039132, -74.127937864373)"
1533514,INITIAL,1821923,PO1821923,1,3017930024,3,1793,24,266,CLIFTON PLACE,11216.0,997105.0,190166.0,40.688630,-73.953646,Brooklyn,10/05/2018 08:06:53 AM,Passed Inspection,10/15/2018 09:30:20 AM,"(40.6886302827724, -73.9536456815219)"
1533515,INITIAL,1821697,PO1821697,1,3016100027,3,1610,27,930,LAFAYETTE AVENUE,11221.0,1002239.0,191220.0,40.691513,-73.935131,Brooklyn,10/09/2018 01:59:50 PM,Passed Inspection,10/15/2018 09:37:26 AM,"(40.6915134335381, -73.9351305479081)"
1533516,INITIAL,1820866,PO1820866,1,3012170071,3,1217,71,571,ST MARKS AVENUE,11216.0,996795.0,185546.0,40.675950,-73.954772,Brooklyn,10/11/2018 09:51:24 AM,Passed Inspection,10/15/2018 08:35:47 AM,"(40.6759499123816, -73.9547718227122)"
1533517,COMPLIANCE,1805139,PO1782499,2,3013870013,3,1387,13,1604,ST JOHNS PLACE,11233.0,1005172.0,183467.0,40.670220,-73.924579,Brooklyn,09/24/2018 02:55:51 PM,Passed Inspection,10/15/2018 12:12:20 PM,"(40.670219540776, -73.924579476025)"
1533518,BAIT,439894,PO1701226,8,1021700003,1,2170,3,4388,BROADWAY,10040.0,1002719.0,250590.0,40.854468,-73.933242,Manhattan,10/12/2018 11:10:53 AM,Bait applied,10/15/2018 11:35:24 AM,"(40.8544679918452, -73.9332424424587)"
1533519,INITIAL,1816045,PO1816045,1,3033570028,3,3357,28,36,WOODBINE STREET,11221.0,1006544.0,190525.0,40.689589,-73.919610,Brooklyn,10/05/2018 03:01:48 PM,Active Rat Signs,10/15/2018 04:23:11 PM,"(40.689588795047, -73.919610194637)"
1533520,INITIAL,1823997,PO1823997,1,3031580030,3,3158,30,152,KNICKERBOCKER AVENUE,11237.0,1004147.0,195825.0,40.704149,-73.928235,Brooklyn,10/11/2018 03:10:07 PM,Passed Inspection,10/15/2018 09:47:55 AM,"(40.7041493167177, -73.9282352844359)"
1533521,INITIAL,1824021,PO1824021,1,3031580114,3,3158,114,130,GEORGE STREET,11237.0,1003904.0,195562.0,40.703428,-73.929112,Brooklyn,10/12/2018 11:40:23 AM,Passed Inspection,10/15/2018 09:47:48 AM,"(40.7034276537956, -73.9291120202317)"
1533522,BAIT,439892,PO1722756,9,1021770150,1,2177,150,427,FT WASHINGTON AVENUE,10033.0,1001077.0,248809.0,40.849588,-73.939182,Manhattan,10/12/2018 10:25:24 AM,Monitoring visit,10/15/2018 11:34:46 AM,"(40.8495879599208, -73.9391819608305)"

In [5]:
rats_count = rats.groupby("ZIP_CODE").INSPECTION_TYPE.count().sort_values(ascending=False).reset_index()

In [6]:
rats_count.shape

(198, 2)

In [7]:
rats.shape

(1533523, 20)

In [8]:
rats_count["INSPECTION_TYPE"].sum()

1533497

In [9]:
rats_count.to_csv("rats.csv")